### ISSUE TITLE
pass Java system properties–aws.accessKeyId and aws.secretKey to pod

### ISSUE THREAD

**Issue by digash** [babashka/pod-babashka-aws#14]
The second [default way to auth](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) is to use Java system properties–aws.accessKeyId and aws.secretKey. The AWS SDK for Java uses the [SystemPropertiesCredentialsProvider ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/SystemPropertiesCredentialsProvider.html) to load these credentials.

These properties currently not passed along to pod.

**Comment by borkdude** [comment]
Fixed using @jeroenvandijk's PR
