### ISSUE TITLE
awsSession is not passed into system-properties

### ISSUE THREAD

**Issue by digash** [babashka/pod-babashka-aws#21]
#14 missed "aws.sessionToken" system property that is needed for auth to work
It was not working upstream either, they fixed it cognitect-labs/aws-api#167 [Released in aws-api 0.8.498](https://github.com/cognitect-labs/aws-api/commit/e333d5357de1c93551b902189ab7220e0f487a6b)

I can submit a pull request but it is trivial change, just need to add it to the list at
[credentials.clj line 187](https://github.com/babashka/pod-babashka-aws/blob/acde9cb7ace1128e484ddaf43e5b2d8fb0d37000/src/pod/babashka/aws/impl/aws/credentials.clj#L187)

Also would be good to update deps.edn aws-api reference to 0.8.498 version.

**Comment by borkdude** [comment]
@digash PR welcome. I'll update the deps tomorrow and will make a new release with your PR included.

**Comment by digash** [comment]
@borkdude pull request created

**Comment by borkdude** [comment]
Thanks. You could try if this works for you with a build from CI, to make sure everything works.
