### ISSUE TITLE
problems with invoking lambda and apigateway

### ISSUE THREAD

**Issue by judepayne** [babashka/pod-babashka-aws#27]
Hi, was able to work with s3 (as per the examples and tests) without any issues at all but had this error when trying with `lambda`

    (def lambda (aws/client {:api :lambda :region "eu-west-2"}))
    (aws/invoke lambda {:op :ListFunctions})
resulted in

    clojure.lang.ExceptionInfo: No implementation of method: :wrap-object of protocol: #'pod.babashka.aws.impl.aws/IWrapObject found for class: nil

I had the same error when testing a call to `apigateway` as well.
thanks!

**Comment by borkdude** [comment]
@judepayne Which OS are you using? I will provide you with a binary for testing that you can load with:

```
(pods/load-pod "./pod-babashka-aws")
```

**Comment by judepayne** [comment]
Thanks. I'm on MacOS

**Comment by borkdude** [comment]
@judepayne Ok, please try this one: 

https://231-325868827-gh.circle-artifacts.com/0/release/pod-babashka-aws-0.0.4-macos-amd64.zip

**Comment by judepayne** [comment]
perfect - various lambda and apigateway invocations all now work!

**Comment by borkdude** [comment]
@judepayne v0.0.5 released.

@vharmain I tried adding:

```
(def lambda (aws/client {:api :lambda :region "eu-west-2"}))
(aws/invoke lambda {:op :ListFunctions})
```

as a test in the test script against localstack.

Using the normal `aws-api` from a Clojure REPL this worked (when adding in the endpoint overrides, etc), but with the pod I got:

```
#:cognitect.anomalies{:category :cognitect.anomalies/incorrect}
```

without any additional information. If possible, it would be nice to add this to the tests, so it won't break in the future.

**Comment by borkdude** [comment]
Created a new issue for it.

**Comment by judepayne** [comment]
Great will continue to test with v0.0.5
