### ISSUE TITLE
Add lambda test to CI

### ISSUE THREAD

**Issue by borkdude** [babashka/pod-babashka-aws#28]
See #27

@vharmain I tried adding:

```
(def lambda (aws/client {:api :lambda :region "eu-west-2"}))
(aws/invoke lambda {:op :ListFunctions})
```

as a test in the test script against localstack.

Using the normal `aws-api` from a Clojure REPL this worked (when adding in the endpoint overrides, etc), but with the pod I got:

```
#:cognitect.anomalies{:category :cognitect.anomalies/incorrect}
```

without any additional information. If possible, it would be nice to add this to the tests, so it won't break in the future.

_Originally posted by @borkdude in https://github.com/babashka/pod-babashka-aws/issues/27#issuecomment-765308963_

**Comment by vharmain** [comment]
@borkdude the problem was probably that `lambda` was not enabled in localstack. See https://github.com/babashka/pod-babashka-aws/pull/29
