### ISSUE TITLE
Broken message when missing GRAALVM_HOME

### ISSUE THREAD

**Issue by lasiltan** [babashka/pod-babashka-aws#32]
in `script/compile`, missing GRAALVM_HOME is handled as such:

```bash
if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set $GRAALVM_HOME"
    exit 1
fi
```

Resulting in the message `Please set`. Should be:

```bash
if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi
```

**Comment by borkdude** [comment]
I agree. PR welcome.

**Comment by lasiltan** [comment]
> I agree. PR welcome.

I don't think I have access to make a pr.

**Comment by borkdude** [comment]
Anyone can make a pull request against this repo. Only people with access can accept it.

**Comment by lasiltan** [comment]
https://github.com/babashka/pod-babashka-aws/pull/34

**Comment by borkdude** [comment]
Thanks!
