### ISSUE TITLE
Link static build against musl

### ISSUE THREAD

**Issue by borkdude** [babashka/pod-babashka-aws#36]
See oracle/graal#2691 (comment)
Linking against the host glibc is a bad idea, we should link against musl for all of our static builds.
Then perhaps all the weird segmentation faults etc are over...

@lispyclouds will try to do this for pod-babashka-aws first.

/cc @thiagokokada @ericdallo @lispyclouds

**Comment by lispyclouds** [comment]
@thiagokokada @ericdallo @borkdude got it to build and the tests to pass! have a look on the [musl](https://github.com/babashka/pod-babashka-aws/tree/musl) branch, let me know if it could be done better?

**Comment by lispyclouds** [comment]
Closed by #37
