### ISSUE TITLE
linux aarch64 release

### ISSUE THREAD

**Issue by brandonstubbs** [babashka/pod-babashka-aws#46]
Can we please include an `aarch64` release as babashka supports this architecture?

```Dockerfile
FROM arm64v8/ubuntu

RUN apt update
RUN apt install -y curl

RUN curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install && \
    chmod +x install && \
    ./install

RUN bb "(babashka.pods/load-pod 'org.babashka/aws \"0.1.0\")"
```

Test build by running:
```bash
docker build -t aws-arm .
```

Error on missing executable for arch:
```
#9 0.394 ----- Error --------------------------------------------------------------------
#9 0.394 Type:     java.lang.IllegalArgumentException
#9 0.394 Message:  No executable found for pod org.babashka/aws (0.1.0) and OS Linux/aarch64
#9 0.394 Location: <expr>:1:1
#9 0.394 
#9 0.394 ----- Context ------------------------------------------------------------------
#9 0.395 1: (babashka.pods/load-pod 'org.babashka/aws "0.1.0")
#9 0.395    ^--- No executable found for pod org.babashka/aws (0.1.0) and OS Linux/aarch64
#9 0.395 
#9 0.395 ----- Stack trace --------------------------------------------------------------
#9 0.395 user - <expr>:1:1
#9 0.395 
------
```

Please let me know if you don't have time to alter the cicd pipelines, I can try to get some time to do this.

Thanks!! 😎

**Comment by borkdude** [comment]
@brandonstubbs Yes. If you or me or someone else who has time wants to make a PR to the CircleCI config similar to how babashka is built on aarch64, we can get this working. I'll also notify @lispyclouds as he may be interested in it too.

**Comment by borkdude** [comment]
@tjefferson08 Sorry, I merged to early. The `linux-aarch64` config wasn't included in the `jobs` at the end of the config and turned out to not work at all. Feel free to look at the babashka circleci config which includes a linux-aarch64 config. I also recommend using the static approach by default as this works best on linux machines that do not have libz etc installed.

**Comment by tjefferson08** [comment]
@borkdude thanks for the guidance, I'll have another look as soon as I can!

**Comment by cap10morgan** [comment]
@tjefferson08 If it's alright with you I'm going to look into this today. I need it at $dayjob and I'm the one who did the work on https://github.com/babashka/babashka/pull/1099 so hopefully can get this building w/ a similar approach.

**Comment by borkdude** [comment]
@cap10morgan We don't need to build docker images for this pod, it's much simpler. Just a CircleCI config similar to what babashka has for aarch64 should be sufficient.

**Comment by cap10morgan** [comment]
> @cap10morgan We don't need to build docker images for this pod, it's much simpler. Just a CircleCI config similar to what babashka has for aarch64 should be sufficient.

Yes, sorry. I didn't intend to imply otherwise. :)

**Comment by tjefferson08** [comment]
@cap10morgan by all means! I'm rooting for you

**Comment by borkdude** [comment]
The aarch64 is available on Github releases and also via the pod registry.
