### ISSUE TITLE
 Add credentials interface

### ISSUE THREAD

**Issue by borkdude** [babashka/pod-babashka-aws#5]
Oh and in addition I'm still thinking about how to integrate the credential interface for custom setups. But it's already usable without this addition through AWS environment vars.

 Add credentials interface
 
 - [x] initial PR by @jeroenvandijk 
 - [x] add better parser for credentials_process @borkdude 
 - [x] fix CI: I guess we can write the built artifact and then do the tests in another job. Right now the build is OOM-ing. cc @vharmain

**Comment by bhurlow** [comment]
Though the cognitect library uses a protocol to provide credentials, I feel that being able to simply pass the aws key and secret into the client map, or some shim around `basic-credentials-provider` could be worthwhile for general scripting

**Comment by borkdude** [comment]
@bhurlow #16 is a work in progress PR by @jeroenvandijk - you might also want to look at this and leave feedback
